export const GET_SITE_META = 'GET_SITE_META';
export const GET_SITE_META_SUCCESS = 'GET_SITE_META_SUCCESS';
export const GET_SITE_META_FAILED = 'GET_SITE_META_FAILED';

export const SET_APP_ERROR = 'SET_APP_ERROR';
export const SET_APP_LOADING = 'SET_APP_LOADING';
