export const CLEAR_WORDS = 'CLEAR_WORDS';
export const GET_WORDS = 'GET_WORDS';
export const GET_WORDS_SUCCESS = 'GET_WORDS_SUCCESS';
export const GET_WORDS_FAILED = 'GET_WORDS_FAILED';

export const CLEAR_FEATURED_WORDS = 'CLEAR_FEATURED_WORDS';
export const GET_FEATURED_WORDS = 'GET_FEATURED_WORDS';
export const GET_FEATURED_WORDS_SUCCESS = 'GET_FEATURED_WORDS_SUCCESS';
export const GET_FEATURED_WORDS_FAILED = 'GET_FEATURED_WORDS_FAILED';
