export const GET_WORD_CATEGORY = 'GET_WORD_CATEGORY';
export const GET_WORD_CATEGORY_WORD = 'GET_WORD_CATEGORY_WORD';
export const GET_WORD_CATEGORY_SUCCESS = 'GET_WORD_CATEGORY_SUCCESS';
export const GET_WORD_CATEGORY_WORDS_SUCCESS = 'GET_WORD_CATEGORY_WORDS_SUCCESS';
export const GET_WORD_CATEGORY_FAILED = 'GET_WORD_CATEGORY_FAILED';
export const GET_WORD_CATEGORY_WORDS_FAILED = 'GET_WORD_CATEGORY_WORDS_FAILED';
export const CLEAR_WORD_CATEGORY = 'CLEAR_WORD_CATEGORY';
export const CLEAR_WORD_CATEGORY_WORDS = 'CLEAR_WORD_CATEGORY_WORDS';
