export const CLEAR_WORD_SEARCH_RESULTS = 'CLEAR_WORD_SEARCH_RESULTS';
export const GET_WORD_SEARCH_RESULTS = 'GET_WORD_SEARCH_RESULTS';
export const GET_WORD_SEARCH_RESULTS_SUCCESS = 'GET_WORD_SEARCH_RESULTS_SUCCESS';
export const GET_WORD_SEARCH_RESULTS_FAILED = 'GET_WORD_SEARCH_RESULTS_FAILED';

export const CLEAR_POST_SEARCH_RESULTS = 'CLEAR_POST_SEARCH_RESULTS';
export const GET_POST_SEARCH_RESULTS = 'GET_POST_SEARCH_RESULTS';
export const GET_POST_SEARCH_RESULTS_SUCCESS = 'GET_POST_SEARCH_RESULTS_SUCCESS';
export const GET_POST_SEARCH_RESULTS_FAILED = 'GET_POST_SEARCH_RESULTS_FAILED';
