export const GET_WORD_TAGS = 'GET_WORD_TAGS';
export const GET_WORD_TAGS_SUCCESS = 'GET_WORD_TAGS_SUCCESS';
export const GET_WORD_TAGS_FAILED = 'GET_WORD_TAGS_FAILED';
export const CLEAR_WORD_TAGS = 'CLEAR_WORD_TAGS';
