export const GET_WORD_CATEGORIES = 'GET_WORD_CATEGORIES';
export const GET_WORD_CATEGORIES_SUCCESS = 'GET_WORD_CATEGORIES_SUCCESS';
export const GET_WORD_CATEGORIES_FAILED = 'GET_WORD_CATEGORIES_FAILED';
