import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faAws,
  faBitbucket,
  faCss3,
  faFacebook,
  faFacebookF,
  faFacebookSquare,
  faGit,
  faGithub,
  faGoogle,
  faHtml5,
  faInstagram,
  faLinkedin,
  faLinkedinIn,
  faNodeJs,
  faPhp,
  faPython,
  faTwitter,
  faTwitterSquare,
  faWhatsapp,
  faWhatsappSquare,
  faYoutube,
  faYoutubeSquare,
} from '@fortawesome/free-brands-svg-icons';
import {
  faAd,
  faAnalytics,
  faAngleDoubleRight,
  faArrowUp,
  faAtomAlt,
  faBooks,
  faBracketsCurly,
  faBrowser,
  faBuilding,
  faChartLine,
  faCheck,
  faCode,
  faCodeBranch,
  faCodeCommit,
  faEnvelope,
  faEnvelopeSquare,
  faFont,
  faIcons,
  faLink,
  faNewspaper,
  faObjectGroup,
  faPaintBrush,
  faPalette,
  faServer,
  faSitemap,
  faTerminal,
  faTimes,
  faTint,
  faUsers,
} from '@fortawesome/pro-regular-svg-icons';
import {
  faHandsHelping,
  faHeart,
  faPhone,
  faSearch,
} from '@fortawesome/pro-solid-svg-icons';

export enum EFontAwesomeType {
  solid = 'fas',
  regular = 'far',
  light = 'fal',
  brand = 'fab',
  duotone = 'fad',
}

/**
 * Add Fontawesome icons to library for app
 */
export default {
  init: () =>
    library.add(
      faHandsHelping,
      faHtml5,
      faCss3,
      faPhone,
      faChartLine,
      faBrowser,
      faTimes,
      faCode,
      faBracketsCurly,
      faTerminal,
      faCodeCommit,
      faCodeBranch,
      faAtomAlt,
      faTint,
      faPaintBrush,
      faPalette,
      faBooks,
      faAngleDoubleRight,
      faFont,
      faCheck,
      faArrowUp,
      faSitemap,
      faAnalytics,
      faServer,
      faUsers,
      faIcons,
      faAd,
      faObjectGroup,
      faYoutube,
      faYoutubeSquare,
      faNewspaper,
      faBuilding,
      faSearch,
      faHeart,
      faFacebookSquare,
      faFacebook,
      faFacebookF,
      faGit,
      faWhatsappSquare,
      faWhatsapp,
      faEnvelope,
      faEnvelopeSquare,
      faAws,
      faNodeJs,
      faGoogle,
      faPhp,
      faPython,
      faTwitter,
      faTwitterSquare,
      faInstagram,
      faLinkedin,
      faLinkedinIn,
      faGithub,
      faBitbucket,
      faLink
    ),
};
